FROM ubuntu:21.04

ENV DEBIAN_FRONTEND=noninteractive
ENV PYTHONDONTWRITEBYTECODE=1
RUN apt update && apt install -y python3.8 curl python3-distutils python3-pip
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

COPY . /app
WORKDIR /app

RUN rm /bin/sh && ln -s /bin/bash /bin/sh
RUN source $HOME/.poetry/env && \
    poetry config virtualenvs.create false && \
    poetry install
