FROM ubuntu:21.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y curl sudo gnupg
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
RUN apt update && apt install -y nodejs yarn

COPY . /app
WORKDIR /app
RUN yarn install
